spring:
  application:
    name: user-service
  output:
    ansi:
      enabled: ALWAYS
  jpa:
    generate-ddl: true
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: create
  datasource:
    username: ${MYSQL_USER}
    password: ${MYSQL_PASSWORD}
    url: jdbc:mysql://${MYSQL_DB_URL}:${MYSQL_DB_PORT}/k8
    driver-class-name: com.mysql.cj.jdbc.Driver
  data:
    mongodb:
      authentication-database: admin
      username: ${MONGO_USER}
      password: ${MONGO_PASSWORD}
      database: ${MONGO_DB_NAME}
      port: ${MONGO_DB_PORT}
      host: ${MONGO_DB_HOST}

server:
  port: 9001